default:
  image: ubuntu:latest

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo $_AIRFLOW_WWW_USER_USERNAME
    - echo "I am here" >> log-gitlab-runner-yawn.txt
  artifacts:
    paths:
      - log-gitlab-runner-yawn.txt
    expire_in: 3 days

deploy-prod:
  stage: deploy
  before_script:
    - ls -la
    - pwd
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat $SSH_KEY_EC2
    - echo "$(cat $SSH_KEY_EC2)" >> ~/.ssh/ammaru.pem
    - chmod 400 ~/.ssh/ammaru.pem
    - cat ~/.ssh/ammaru.pem
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - apt-get update -y
    - apt-get -y install rsync
  script:
    - ssh -i ~/.ssh/ammaru.pem -v ubuntu@$EC2_ADDRESS "pwd && ls -la && git config --global user.name "Ammar Chalifah" && git config --global user.email "ammar.chalifah@gmail.com" && if [git show-ref q --heads main]; then git pull; else git clone https://ammarchalifah:sixsome1598Edu@gitlab.com/marukun/airflow-pipeline.git; fi && docker-compose down && docker-compose up airflow-init && docker-compose up -d"