default:
  image: ruby:2.6

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo $_AIRFLOW_WWW_USER_USERNAME

test-job:
  stage: test
  script: 
    - echo "This job tests something"

deploy-prod:
  stage: deploy
  only:
    - main
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."